### ISSUE TITLE
ArgoCD can't find SSH key for github repositor

### ISSUE THREAD

**Issue by ltshb** [dag-andersen/argocd-diff-preview#113]
I'm trying out the tool for an ArgoCD setup that uses SSH to clone github repository and I go the following error 

```bash
[2025-03-07T08:13:36Z ERROR argocd_diff_preview::extract] ❌ my-app, Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to list refs: ssh: no key found
```

In my application manifest the source is set as follow

```yaml
source:
    repoURL: git@github.com:my-org/my-repo.git
    targetRevision: main
    path: services/my-service
```

The repository is private so I used the following code to pass the private SSH key that I use in my argoCD cluster

```yaml
- name: Prepare secrets
  env:
    # We need to put the secret in an environment variable in order to avoid indentation issue
    # when creating the secret below.
    REPO_ACCESS_SSH_PRIVATE_KEY: |
      ${{ secrets.REPO_ACCESS_SSH_PRIVATE_KEY }}
  run: |
    mkdir secrets
    cat > secrets/secret.yaml << EOF
    apiVersion: v1
    kind: Secret
    metadata:
      name: private-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      type: git
      url: git@github.com:my-org/my-repo.git
      sshPrivateKey: |
        ${REPO_ACCESS_SSH_PRIVATE_KEY}
    EOF
```

And finally I start the difftool like this

```yaml
- name: Generate Diff
  run: |
    docker run \
      --network=host \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(pwd)/base:/base-branch \
      -v $(pwd)/pull-request:/target-branch \
      -v $(pwd)/output:/output \
      -v $(pwd)/secrets:/secrets \
      -e SECRETS_FOLDER=/secrets \
      -e BASE_BRANCH=${{ github.base_ref }} \
      -e TARGET_BRANCH=${{ github.head_ref }} \
      -e REPO=${{ github.repository }} \
      dagandersen/argocd-diff-preview:v0.0.35 --debug
```

Any idea why I got this error or how I could debug it ?

**Comment by dag-andersen** [comment]
Hi @ltshb ! 

Is there a reason you choose to use SSH instead of the ephemeral token that GitHub creates for you automatically?

```yaml
    - name: Prepare secrets
      run: |
        mkdir secrets
        cat > secrets/secret.yaml << "EOF"
        apiVersion: v1
        kind: Secret
        metadata:
          name: private-repo
          namespace: argocd
          labels:
            argocd.argoproj.io/secret-type: repo-creds
        stringData:
          url: https://github.com/${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}  ⬅️ Short-lived GitHub Token
          username: not-used
        EOF
```

The error you are seeing comes from Argo CD in the `my-app` application, so it is not specific to `argocd-diff-preview`.

If you want to dig deeper and have access to the REPO_ACCESS_SSH_PRIVATE_KEY secret on your local machine, you can always try running the tool locally and inspect Argo CD/the cluster.

```
mkdir secrets
cat > secrets/secret.yaml << EOF
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:my-org/my-repo.git
  sshPrivateKey: |
    ${REPO_ACCESS_SSH_PRIVATE_KEY}
EOF

git clone https://github.com/<owner>/<repo> base-branch --depth 1 -q -b <branch-a>
git clone https://github.com/<owner>/<repo> target-branch --depth 1 -q -b <branch-b>

docker run \
  --network host \
  -v ~/.kube:/root/.kube \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(pwd)/output:/output \
  -v $(PWD)/secrets:/secrets \
  -v $(pwd)/base-branch:/base-branch \
  -v $(pwd)/target-branch:/target-branch \
  -e TARGET_BRANCH=<branch-a> \
  -e BASE_BRANCH=<branch-b> \
  -e REPO=<owner>/<repo>  \
  dagandersen/argocd-diff-preview:v0.0.34 \
  --debug \
  --keep-cluster-alive

argocd login --core
kubectl config set-context --current --namespace=argocd
argocd admin dashboard
```

and now you should be able to use `kubectl` and `argocd` commands from you local machine and inspect the cluster 🚀
