### ISSUE TITLE
No support for ArgoCD Applications with multiple sources

### ISSUE THREAD

**Issue by gozer** [dag-andersen/argocd-diff-preview#131]
This is a lesser known but supported ArgoCD Application feature

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```

When in use, however, argocd-diff just fails to find a source to patch, as can be seen here:

```
DBG Found no 'targetRevision' under spec.source (file: application.yaml) (patchType: redirectSource)
```

See-Also: [ArgoCD: Multiple Sources for an Application](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/)

**Comment by dag-andersen** [comment]
Hi @gozer,

Thank you for showing interest in the project. The tool should support multiple sources just fine - there are several examples of this in our integration tests - so let’s figure out what’s happening here :)

Would you mind sharing a bit more of the logs so I can get some context?

Also, could you show me the arguments the tool was run with? (All the logs that start with a "✨")

**Comment by gozer** [comment]
I am a big fan of the project and very thankful someone decided to write it 
before I ended up having to!

I didn't realize it was supported and I'll admit I mostly concluded it wasn't because of log messages.

I can have a closer look and see:
 - if it's actually broken for me
 - if I could make a reproducible test case

I'll update this issue once I have more.

**Comment by yolkov** [comment]
The issue here is most likely that the repository for $values points to a “future” branch.
For example, with the following:

- repoURL: 'https://git.example.com/org/value-files.git'
  targetRevision: dev
  ref: values

argocd-diff-preview will fetch values from the dev branch, but the changes are in the pull request(current branch), so the diff will be empty.
You need to change the logic in argocd-diff-preview, if TARGET_BRANCH = 'dev', then argocd-diff-preview should override "targetRevision:' with the current branch; if they don’t match, then fall back to using 'dev'.

**Comment by upodroid** [comment]
This still doesn't work.

Have a look at this:
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/k8s.io/9936/pull-k8sio-argocd-diff/2099898428350795776

```
git clone --depth 1 https://github.com/kubernetes/k8s.io /tmp/base-branch
kind create cluster
helm repo add argo https://argoproj.github.io/argo-helm
helm upgrade --install argocd argo/argo-cd --version 10.8.4 --create-namespace --namespace argocd-diff-preview \
  --set configs.cm."kustomize\.buildOptions"="--load-restrictor LoadRestrictionsNone --enable-alpha-plugins"
kubectl apply -n argocd-diff-preview -f kubernetes/gke-utility/argocd/clusters.yaml || true # ignore errors from missing ES
kubectl apply -n argocd-diff-preview -f kubernetes/gke-utility/argocd/clusters-diff.yaml # ES based clusters

docker run \
  --network=host \
  -v ~/.kube:/root/.kube \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/base-branch:/base-branch \
  -v $(pwd):/target-branch \
  -v /logs/artifacts:/output \
  -e TARGET_BRANCH=$PULL_PULL_SHA \
  -e REPO=$REPO_OWNER/$REPO_NAME \
  dagandersen/argocd-diff-preview:v0.2.14 \
  --argocd-namespace=argocd-diff-preview \
  --timeout=240 \
  --create-cluster=false
```
- app definition: https://github.com/kubernetes/k8s.io/blob/main/kubernetes/apps/mimir.yaml
- diff output: https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/k8s.io/9936/pull-k8sio-argocd-diff/2099898428350795776/artifacts/diff.html

**Comment by dag-andersen** [comment]
@upodroid 

I investigated the CI job linked in the newest comment and reproduced the behavior locally using the same repository revisions, Argo CD chart version, and `argocd-diff-preview:v0.2.14`.

The multiple-source `$values` configuration seems to be working correctly.

However the reason you are not seeing an output is that the `mimir` `ApplicationSet` uses a Cluster Generator with this selector:

```yaml
generators:
  - clusters:
      selector:
        matchLabels:
          clusterType: utility
```

The CI environment did not register any Argo CD cluster Secret with the label `clusterType: utility`. As a result, the ApplicationSet generated zero Applications on both the base and target revisions. The logs show:

```text
ApplicationSet generated empty output
```

The tool then continued rendering the other Applications and ultimately produced `No changes found`. The Mimir Application was not included in that comparison.

I confirmed this by adding the following dummy Cluster Secret and rerunning the comparison:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gke-utility
  labels:
    name: gke-utility
    argocd.argoproj.io/secret-type: cluster
    clusterType: utility
type: Opaque
stringData:
  name: gke-utility
  server: https://kubernetes.default.svc
  config: {}
```

The Secret was applied to the Argo CD namespace. It does not need valid cluster credentials because `argocd-diff-preview` only renders manifests and does not deploy to the target cluster.

With this Secret present, the Mimir Application was generated for both revisions, and the tool correctly:

- Kept the Grafana Helm chart pinned at `6.1.0`
- Redirected the values source to the base and target revisions
- Redirected the manifests source to the base and target revisions
- Produced the expected changes to the Mimir limits and ingester replicas

For Cluster Generator based ApplicationSets, `argocd-diff-preview` needs dummy Cluster Secrets so Argo CD can generate the Applications. The required setup is described here:

https://dag-andersen.github.io/argocd-diff-preview/cluster-generator/

let me know if that helps :)
