### ISSUE TITLE
Cannot run argocd-diff-preview with the latest v0.1.4 | `PermissionDenied`

### ISSUE THREAD

**Issue by onstring** [dag-andersen/argocd-diff-preview#145]
We've been using this tool in our CI jobs for all ArgoCD changes for a while, but the job stopped working on April 21st when we updated to the v0.1.4 image. We've tested several changes to rule out any invalid ArgoCD configuration issues, but it appears the problem is only related to the image version change.

v0.1.3 is working
v0.1.4 is not working for all our argocd changes

The error is obscure and there is not any useful information even with --debug.

> 🤖 Getting resources from branch (branch: refs/changes/36/55536/3)
> ❌ Failed to get manifests for application: kubernetes-event-exporter, error: failed to get manifests: exit status 20
> ❌ Failed to process application: kubernetes-event-exporter with error: 
> failed to get manifests: exit status 20
> ❌ Failed to extract resources
> 💥 Deleting cluster...
> 💥 Cluster deleted successfully
> ❌ failed to get resources: failed to process applications

Could I please have any advice about this?

---

Please give this post a 👍🏻 if you also experience this issue

**Comment by dag-andersen** [comment]
Thank you for reporting this! 🔥 

Would you mind sharing the `kubernetes-event-exporter` application manifest?

After I rewrote the tool from Rust to Go, some of the error messages got worse. I've now created a new release: [v0.1.5-pre-release](https://github.com/dag-andersen/argocd-diff-preview/releases/tag/v0.1.5-pre-release) (image: `dagandersen/argocd-diff-preview:v0.1.5-pre-release-22ee20b`). Hopefully, this version has better log messages for that specific error 🚀

**Comment by onstring** [comment]
Thanks for the support. 

The manifest is actually quite simple, I just submit a fake change to update the elasticsearch host for the CI jobs testing.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: kubernetes-event-exporter
    targetRevision: 3.4.5
    helm:
      values: |
        config:
          logLevel: info
          logFormat: json
          metricsNamePrefix: event_exporter_
          receivers:
            - name: "elasticsearch-dump"
              elasticsearch:
                hosts:
                  - http://<host1>:9200
                indexFormat: "kube-events-{2006-01-02}"
          route:
            routes:
              - match:
                  - receiver: "elasticsearch-dump"
```

Also with your new image, I see some strange permission related error, is that maybe something with our environment setting?

> 🦑 Argo CD installed successfully
> 🤖 Converting ApplicationSets to Applications in both branches
> 🤖 No ApplicationSets found for branch: master
> 🤖 No ApplicationSets found for branch: refs/changes/36/55536/3
> W0425 11:11:42.810799       1 warnings.go:70] metadata.finalizers: "resources-finalizer.argocd.argoproj.io": prefer a domain-qualified finalizer name including a path (/) to avoid accidental conflicts with other finalizer writers
> 🤖 Getting resources from branch (branch: master)
> 🤖 Got all resources from 1 applications (branch: master)
> 🧼 Deleting applications
> 🧼 Deleted applications
> 🤖 Getting resources from branch (branch: refs/changes/36/55536/3)
> ❌ Failed to get manifests for application: kubernetes-event-exporter, error: failed to get manifests: E0425 11:11:53.389888     718 portforward.go:385] "Unhandled Error" err="error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:32899->127.0.0.1:42146: write tcp4 127.0.0.1:32899->127.0.0.1:42146: write: broken pipe" logger="UnhandledError"
> time="2025-04-25T11:11:53Z" level=fatal msg="rpc error: code = PermissionDenied desc = permission denied"
> : exit status 20
> ❌ Failed to process application: kubernetes-event-exporter with error: 
> failed to get manifests: E0425 11:11:53.389888     718 portforward.go:385] "Unhandled Error" err="error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:32899->127.0.0.1:42146: write tcp4 127.0.0.1:32899->127.0.0.1:42146: write: broken pipe" logger="UnhandledError"
> time="2025-04-25T11:11:53Z" level=fatal msg="rpc error: code = PermissionDenied desc = permission denied"
> : exit status 20
> ❌ Failed to extract resources
> 💥 Deleting cluster...
> 💥 Cluster deleted successfully
> ❌ failed to get resources: failed to process applications
> 🕵️ Run with '--debug' for more details

**Comment by dag-andersen** [comment]
@onstring  Alright, interesting 🕵 I think those permission errors usually happen because of network issues.

Sadly, I am not able to reproduce it 😕 I created the App on a branch [bug-report-145](https://github.com/dag-andersen/argocd-diff-preview/blob/bug-report-145/examples/random-app.yaml)

If I run ⬇ on my local machine, it doesn't fail and It creates the correct diff.
```
git clone https://github.com/dag-andersen/argocd-diff-preview base-branch --depth 1 -q
git clone https://github.com/dag-andersen/argocd-diff-preview target-branch --depth 1 -q -b bug-report-145
docker run \
   --network host \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v $(pwd)/output:/output \
   -v $(pwd)/base-branch:/base-branch \
   -v $(pwd)/target-branch:/target-branch \
   -e TARGET_BRANCH=bug-report-145 \
   -e REPO=dag-andersen/argocd-diff-preview \
   dagandersen/argocd-diff-preview:v0.1.4
```

```
🤖 Getting resources from branch (branch: bug-report-145)
🤖 Got all resources from 18 applications (branch: bug-report-145)
🔮 Generating diff between main and bug-report-145
🙏 Please check the ./output/diff.md file for differences
💥 Deleting cluster...
💥 Cluster deleted successfully
✨ Total execution time: 1m45s
```

Where are you running the tool, and can I see the pipeline?

**Comment by onstring** [comment]
We are using the Gerrit for the change review which would trigger CI jobs in Jenkins. The job is run on Jenkins slave and the script is quite straightforward. Wonder is there any relevant change introduced in v0.1.4 regarding permission?

```
rm -rf base-branch
rm -rf target-branch
tmpdir=`mktemp -d --suffix=_argocd`
mkdir target-branch
mkdir secrets
mv $FILE secrets/secrets.yaml
mv apps* target-branch
mkdir base-branch
git checkout -B master origin/$GERRIT_BRANCH
git pull
git reset --hard
mv apps* base-branch
docker run --network host -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/secrets:/secrets -v ${tmpdir}:/output -v $(pwd)/base-branch:/base-branch -v $(pwd)/target-branch:/target-branch -e TARGET_BRANCH=$GERRIT_REFSPEC -e BASE_BRANCH=$GERRIT_BRANCH -e REPO=$GERRIT_PROJECT dagandersen/argocd-diff-preview:v0.1.4
rm -rf secrets
cat ${tmpdir}/diff.md
```

**Comment by dag-andersen** [comment]
@onstring 
Okay, hmm

> Wonder is there any relevant change introduced in v0.1.4 regarding permission?

I don't think so, no.

I just created two new images from commits between `v0.1.3` and `v0.1.4`:
- `dagandersen/argocd-diff-preview:v0.1.3.2-pre-release-f42c8a5`
- `dagandersen/argocd-diff-preview:v0.1.3.3-pre-release-ea9da1f`

If you try these, it might help identify which commit is breaking it for you :)

**Comment by onstring** [comment]
Thanks @dag-andersen 
I've tested them, both images are breaking for me.

**Comment by dag-andersen** [comment]
@onstring Alright thanks!
That means this PR broke it: https://github.com/dag-andersen/argocd-diff-preview/pull/134
Can you show me the full standard output of the tool running in `--debug` ? I need more context to figure out what is wrong :)

**Comment by onstring** [comment]
No prob, here is the full output from my new test. Not sure if it will help.
[argocd_diff_preview.log](https://github.com/user-attachments/files/19929300/argocd_diff_preview.log)

**Comment by alekhrycaiko** [comment]
Earlier today I was also getting permissionDenied errors on 0.1.5 with the changes below. 

I'm not too clear on the cause. I did test a 0.1.6 pre-release branch and saw issues with my secret format. I'm curious if there were any ways secret management has changed and if it's related? Invalid secrets might cause permission errors hence the wonder.

New error from 0.1.6 pre-release branch:
> 🚀 Cluster created successfully
❌ Failed to install Argo CD
💥 Deleting cluster...
💥 Cluster deleted successfully
❌ failed to apply secrets: failed to apply secret secret.yaml: failed to parse manifest YAML: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}


Manifests:
> apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <redacted>
  namespace: argocd
  annotations:
    argocd-diff-preview/watch-pattern: "<redacted>/.*"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: <redacted>
    server: https://kubernetes.default.svc
  sources:
    - repoURL: <redacted>
      path: "<redacted>"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
Parameters
Your pipeline (if applicable)
diff_argo_applications:
    name: Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: pull-request
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare secrets
        run: |
          mkdir secrets
          cat > secrets/secret.yaml << EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: private-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            url: git@github.com/${{ github.repository }}
            sshPrivateKey: |
          $(echo "${{ secrets.<REDACTED> }}" | sed 's/^/    /')
          EOF
      - name: Run ArgoCD in Github and generate a diff of the result.
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -v $(pwd)/secrets:/secrets \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:v0.1.5

**Comment by LudovicTOURMAN** [comment]
Hey @alekhrycaiko,

Not sure that could be the root cause, but when configuring my secret too, I was having an issue with multi-line private key formatting within the GitHub action.
I figured that while printing my secret file from GitHub action, I noticed that the indentation was not valid YAML.
Whatever solution I tested, I was not able to do it properly with different heredocs notations and used to go with the easy solution of one-line base64 encoding values and setting them in a `data` (not `stringData`) as below:

```yaml
- name: Prepare secrets
  run: |
    mkdir -p secrets
    SSH_PRIVATE_KEY_B64=$(echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -w 0)
    URL_B64=$(echo "git@github.com/${{ github.repository }}" | base64 -w 0)
    cat > secrets/secret.yaml <<-EOF
    apiVersion: v1
    kind: Secret
    metadata:
      name: github-repo-ssh
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repo-creds
    data:
      url: "${URL_B64}"
      sshPrivateKey: "${SSH_PRIVATE_KEY_B64}"
    EOF
```
Maybe that could help to fix your secret formatting issue
