### ISSUE TITLE
ArgoCD secrets partially created

### ISSUE THREAD

**Issue by LudovicTOURMAN** [dag-andersen/argocd-diff-preview#150]
### Describe the bug
Since recent changes in your repo, I am having an error such as `failed to get git client for repo git@github.com:<org>/<repo>.git`.
And diffs were not working anymore, as it could not download the corresponding manifests.

### Expected behavior
The app ArgoCD app to be successfully created.

### Standard output (with `--debug` flag)
```
Mon, 28 Apr 2025 08:47:36 UTC INF 🚀 Creating cluster...
Mon, 28 Apr 2025 08:48:01 UTC INF 🚀 Cluster created successfully
Mon, 28 Apr 2025 08:48:01 UTC DBG Creating namespace: argocd
Mon, 28 Apr 2025 08:48:01 UTC DBG Created namespace: argocd
Mon, 28 Apr 2025 08:48:01 UTC DBG Applying manifest (kind: Secret) (name: github-org-https) (namespace: argocd) (source: file:secrets/secret.yaml)
Mon, 28 Apr 2025 08:48:01 UTC INF 🤫 Applied 1 secrets
Mon, 28 Apr 2025 08:48:01 UTC INF 🦑 Installing Argo CD Helm Chart version: 'latest'
...
Mon, 28 Apr 2025 08:49:01 UTC DBG Applying manifest (kind: Application) (name: my-app) (namespace: argocd) (source: string)
Mon, 28 Apr 2025 08:49:01 UTC DBG Applied manifest (branch: master)
Mon, 28 Apr 2025 08:49:01 UTC INF 🤖 Getting resources from branch (branch: master)
Mon, 28 Apr 2025 08:49:06 UTC WRN ⚠️ Application: my-app timed out with error: Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to get git client for repo git@github.com:org/repo.git
Mon, 28 Apr 2025 08:49:06 UTC INF 💤 1 Applications timed out
Mon, 28 Apr 2025 08:49:07 UTC INF 🔄 Refreshing application: my-app
...
Mon, 28 Apr 2025 08:52:04 UTC ERR ❌ Timed out after 180 seconds
Mon, 28 Apr 2025 08:52:04 UTC INF ❌ Processed 0 applications, but 1 applications still remain
Mon, 28 Apr 2025 08:52:04 UTC ERR ❌ Applications with 'ComparisonError' errors:
Mon, 28 Apr 2025 08:52:04 UTC ERR ❌ my-app, Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to get git client for repo git@github.com:org/repo.git
Mon, 28 Apr 2025 08:52:04 UTC ERR ❌ Failed to extract resources
Mon, 28 Apr 2025 08:52:04 UTC INF 💥 Deleting cluster...
Mon, 28 Apr 2025 08:52:05 UTC INF 💥 Cluster deleted successfully
Mon, 28 Apr 2025 08:52:05 UTC ERR ❌ failed to get resources: timed out
Mon, 28 Apr 2025 08:52:05 UTC INF 🐛 If you believe this error is caused by a bug, please open an issue on GitHub
Error: Process completed with exit code 1.
```

### Application causing problems (if applicable)
The issue is coming from the secret file that is partially applied.
In my current situation, I'm having a single file with multiple definitions such as:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-org-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/org
  username: username
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-org-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  url: base64-encoded-url
  type: base64-encoded-type
  sshPrivateKey: base64-encoded-ssh-private-key
---
apiVersion: v1
kind: Secret
metadata:
  name: org-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: org/repo
  type: git
  url: git@github.com:org/repo.git
---
apiVersion: v1
kind: Secret
metadata:
  name: org-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: org/repo
  type: git
  url: https://github.com/org/repo.git
```
Once the secret is applied, I can see that only the first secret (`github-org-https`) is created.

### Issue
As I was able to debug the code, I've noticed the issue comes from [a recent rework of this PR](https://github.com/dag-andersen/argocd-diff-preview/pull/134/files#diff-1b9e517b787c295930ab5aa6cb5556a0400a3c90567f8508cfa7d20216b3d49b).
Mostly from [that function](https://github.com/dag-andersen/argocd-diff-preview/pull/134/files#diff-1b9e517b787c295930ab5aa6cb5556a0400a3c90567f8508cfa7d20216b3d49bR228) where the YAML unmarshalling is returning only the first secret when the file contains 4 of them.

### Fix
I have noticed that the function `ApplyManifestFromString` is managing multi-definition nicely, as you are splitting the string with `---` into multiple strings and then unmarshalling them one by one.
I was able to fix this locally by calling that function within `ApplyManifestFromFile` once the file is properly read.

Here is the related PR that uses that fix: https://github.com/dag-andersen/argocd-diff-preview/issues/150
Let me know if that properly fits the app, as you are the best one to confirm/check it.
