### ISSUE TITLE
ArgoCD Differ unable to diff new files

### ISSUE THREAD

**Issue by alekhrycaiko** [dag-andersen/argocd-diff-preview#154]
### Describe the bug

When upgrading to 0.1.4 I noticed that the action was failing to diff files that have yet to be committed to my repo. 
In my case, I have a new repo that I've added the differ into and it diffs correctly on 0.1.1. But once bumping the PR to 0.1.4 last week I was unable to diff new files. I can confirm the behaviour is still broken on 0.1.5.

Note: Once I've committed new files onto the main branches, I have the issue transform into what's referenced in https://github.com/dag-andersen/argocd-diff-preview/issues/145. But, I've spun this issue up separately as these appear like two distinct behaviours.

### Expected behavior

Diff completes instead of failing.

### Standard output (with `--debug` flag)
```
...
Digest: <redacted>
Status: Downloaded newer image for dagandersen/argocd-diff-preview:v0.1.5
✨ Running v0.1.5 (2025-04-25T14:34:01Z) with:
✨ - local-cluster-tool: kind
✨ - cluster-name: argocd-diff-preview
✨ - base-branch: main
✨ - target-branch: <redacted>
✨ - secrets-folder: ./secrets
✨ - output-folder: ./output
✨ - argocd-namespace: argocd
✨ - repo: <redacted>
✨ - timeout: 180 seconds
🤖 Fetching all files for branch (branch: main)
🤖 Found 3 files in dir base-branch (branch: main)
🤖 Which resulted in 0 k8sResources (branch: main)
🤖 Found 0 Application[Sets] (branch: main)
🤖 Fetching all files for branch (branch: redacted)
🤖 Found 12 files in dir target-branch (branch: redacted)
🤖 Which resulted in 5 k8sResources (branch: redacted)
🤖 Found 1 Application[Sets] (branch: redacted)
🤖 Patching 1 Application[Sets] (branch: redacted)
🚀 Creating cluster...
🚀 Cluster created successfully
🤫 Applied 1 secrets
🦑 Installing Argo CD Helm Chart version: 'latest'
🦑 Installed Chart version: '7.8.28' and App version: 'v2.14.11'
🦑 Argo CD Helm chart installed successfully
🦑 Logging in to Argo CD through CLI...
🦑 Argo CD installed successfully
🤖 Converting ApplicationSets to Applications in both branches
🤖 No ApplicationSets found for branch: main
🤖 No ApplicationSets found for branch: redacted
🤖 Getting resources from branch (branch: main)
🤖 Got all resources from 0 applications (branch: main)
🧼 Deleting applications
🧼 Deleted applications
W0428 16:23:45.037560       1 warnings.go:70] metadata.finalizers: "resources-finalizer.argocd.argoproj.io": prefer a domain-qualified finalizer name including a path (/) to avoid accidental conflicts with other finalizer writers
🤖 Getting resources from branch (branch: redacted)
🤖 Got all resources from 1 applications (branch: redacted)
🔮 Generating diff between main and redacted
❌ Failed to generate diff
💥 Deleting cluster...
💥 Cluster deleted successfully
❌ failed to generate diff: failed to commit to base repo: cannot create empty commit: clean working tree
🕵️ Run with '--debug' for more details
Error: Process completed with exit code 1.
```

### Application causing problems (if applicable)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <redacted>
  namespace: argocd
  annotations:
    argocd-diff-preview/watch-pattern: "<redacted>/.*"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: <redacted>
    server: https://kubernetes.default.svc
  sources:
    - repoURL: <redacted>
      path: "<redacted>"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

### Your pipeline (if applicable)
```yaml
diff_argo_applications:
    name: Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: pull-request
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare secrets
        run: |
          mkdir secrets
          cat > secrets/secret.yaml << EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: private-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            url: git@github.com/${{ github.repository }}
            sshPrivateKey: |
          $(echo "${{ secrets.<REDACTED> }}" | sed 's/^/    /')
          EOF
      - name: Run ArgoCD in Github and generate a diff of the result.
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -v $(pwd)/secrets:/secrets \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:v0.1.5

```
