### ISSUE TITLE
Failing to parse secret with sshPrivateKey

### ISSUE THREAD

**Issue by karl-johan-grahn** [dag-andersen/argocd-diff-preview#161]
Whenever I run the action with an SSH private key, it errors out:

```yaml
      - name: Prepare secrets for ArgoCD
        run: |
          mkdir secrets
          cat > secrets/secret.yaml << EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: argoproj-ssh-creds
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            url: git@github.com:${{ github.repository }}
            type: git
            sshPrivateKey: |
          $(echo "${{ steps.import-secrets.outputs.sshPrivateKey }}" | sed 's/^/    /')
          EOF

      - name: Generate Diff
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -v $(pwd)/secrets:/secrets \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:v0.1.6
```

Erroring out with `failed to apply secrets: failed to apply secret secret.yaml: failed to parse manifest YAML: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {} from folder: ./secrets`

Need help understanding where the error is, in the secret, or in ArgoCD, or in the diff tool?

**Comment by dag-andersen** [comment]
Hi @karl-johan-grahn  
The diff preview tool reports that the secret can't be parsed as valid YAML. Could you add a `cat secrets/secret.yaml` command to manually check that the YAML is correctly formatted? :)

Alternatively you can add the sshkey value in base64 format [[related comment]](https://github.com/dag-andersen/argocd-diff-preview/issues/145#issuecomment-2837768809)

Let me know if that helped 🚀

**Comment by karl-johan-grahn** [comment]
the secret looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argoproj-ssh-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:org/repo
  type: git
  sshPrivateKey: |
    ***
    ***
    ***
    ***
    ***
    ***
    ***
```
