### ISSUE TITLE
Can the destination patching be optional?

### ISSUE THREAD

**Issue by aokomorowski** [dag-andersen/argocd-diff-preview#36]
Hi, still working on the CI setup 👋🏻 

I have quite a specific setup I believe, in which I have multiple clusters within Argo with ApplicationSets which generate the Application based on the cluster's labels, e.g:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
   [OMITED]
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: production
                  server_name: <application_instance_identifier>
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  "production_{{server_name}}": enabled
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      [OMITED]
    spec:
      [OMITED]
      destination:
        server: "{{server}}"
```

While the cluster secret looks like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster_name
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
    production_id: enabled
type: Opaque
stringData:
  [OMITED]
```

This approach gives us a lot of control over what is deployed on the K8s cluster with a single look at the cluster's labels (which work like a kind of feature flag here). It's a very handy abstraction, I'd like not to resign from. However, it seems to be not compatible with ArgoCD Diff Preview as the ADP patches all Application/ApplicationSets destinations to `in-cluster` and in my case, it generates false diffs due to those labels selectors/labels templating (as mentioned in #29 ). 

I made a fork locally, where I simply commented out this patching, I manually patched cluster secrets to override `.stringData.server = "https://kubernetes.default.svc"` and it works like a charm, generating diffs with respect to label selectors.

I'd be extremely grateful if this patching could be disabled with a flag. I believe I can provide a PR with this change.

EDIT: nah, I can't deliver such a PR, I don't know Rust enough to write it idiomatically enough (and simply passing a flag via arguments three times doesn't feel right, I believe a sort of global configuration object would work fine), I resort to you, Dag 🙏🏻

**Comment by dag-andersen** [comment]
Hi again :) 
And again, Thank you once more for your interest in the project 🚀 

Could you help me understand the problem in a bit more detail?
Yes, `argocd-diff-preview` will update your `destination.server: "{{server}}"`, but i am not sure why that is a problem.

> in my case, it generates false diffs due to those labels selectors/labels templating

Does Argo CD produce a different result if the `destination.server` field is set directly vs. if it is populated by the  `generators.clusters`?

I just want to make sure I understand your request correctly. You would like to disable patching specifically for 
`spec.template.spec.destination.server`, but keep all the other patches on that file? (e.g. disabling of `syncPolicy` and setting `spec.project: default`)

---

> ADP patches all Application/ApplicationSets destinations

... and just to avoid any confusion - It only patches Applications' sources where `.spec.sources[*].repoURL.contains(<your-org/your-repo>)`. Not sources which point to other URLs :)

**Comment by aokomorowski** [comment]
> Does Argo CD produce a different result if the destination.server field is set directly vs. if it is populated by the generators.clusters?

Yes, as you might remember we're utilizing templating ApplicationSets with cluster's secrets labels for setting specific Helm values (e.g. for selecting the valid DataDog instance). We even use the Server's name in the Application name (like `deployment-{{name}}`).

Take this live example of our DataDog agent deployment:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "datadog-{{name}}"
    spec:
      project: "datadog"
      sources:
        - repoURL: https://helm.datadoghq.com
          chart: datadog-operator
          targetRevision: 1.2.2
          helm:
            releaseName: "datadog"
            valueFiles:
              - $values/deployments/production/datadog/values/{{metadata.labels.datadog_instance}}.yaml
        - repoURL: git@github.com:company/platform.git
          targetRevision: main
          ref: values
        - repoURL: git@github.com:company/platform.git
          targetRevision: main
          path: deployments/production/datadog/manifests
          directory:
            recurse: true
            include: "{credentials,agents}/{{metadata.labels.datadog_instance}}.yaml"
      destination:
        server: "{{server}}"
        namespace: monitoring
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
```

As you can see this ApplicationSet will generate different Applications based on the value of the server's name and the value of cluster's label `datadog_instance`.
