### ISSUE TITLE
Is this project meant to work for App-of-apps pattern?

### ISSUE THREAD

**Issue by davidfrickert** [dag-andersen/argocd-diff-preview#41]
Trying to get this to work on my app-of-apps argocd repo and basically the diff only prints the application manifests. 
Not sure if I'm using the project on a non intended way or if this pattern is not supported.

Basically, I have the following structure:

```
apps
  Chart.yaml
  values.yaml
  templates/
    app1.yaml
    app2.yaml (etc...)
base.yaml
```

The base.yaml is the "app-of-apps" manifest, like so:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd-apps
  project: default
  source:
    path: apps
    repoURL: <my-git-repo>
    targetRevision: master
  syncPolicy:
    automated: {}
```

I pointed argocd-diff-preview to this file, because if i point to the whole repo it tries to read my applications in `apps` folder which have helm templating, and of course it fails to read them.

Essentially my repo commits just show the rendered Application(s), which is not useful at all :disappointed:
