### ISSUE TITLE
Support multiple sources

### ISSUE THREAD

**Issue by rikez** [dag-andersen/argocd-diff-preview#58]
Hello,

Does it currently support diffing when an Application depends on multiple git repo sources? 

Suppose I have the following config in `https://github.com/argocd-repo.git`.
```yaml
sources:
  - repoURL: "charts.internal"
    chart: "chart1"
    targetRevision: "0.1.0"
    helm:
      releaseName: "chart1"
      valueFiles:
        - "values.yaml"
        - "$externalValues/path/to/values.yaml"
  - repoURL: "https://github.com/values-repo.git"
    ref: externalValues
    targetRevision: HEAD
```

 I tried, but it looks like the `REPO` environment variable is checked against all `repoURL` git sources.
