### ISSUE TITLE
ApplicationSet | Git Generators Does not work as expected

### ISSUE THREAD

**Issue by dag-andersen** [dag-andersen/argocd-diff-preview#67]
Currently, applications using Git generators do not detect changes properly.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-name
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/org/repo-name.git
      revision: 🚀🚀🚀🚀🚀🚀🚀    ⬅️     This field is not being updated correctly
```

I am working on a fix.
Please give a "👍" on the issue if you have experienced this problem, so I have an idea of how many people are affected.
