### ISSUE TITLE
[Feature Request] Added ability to generate structed diffs

### ISSUE THREAD

**Issue by ponkio-o** [dag-andersen/argocd-diff-preview#69]
Hi @dag-andersen !

Thank you for developing a great tool!

## Summary
I want the ability to generate structed diffs.

## Background
Currently, argocd-diff-preview using the `git diff` command to generate diff between two branches.
https://github.com/dag-andersen/argocd-diff-preview/blob/a31805d8f590776e1b8f68f21d927dc919dc08d5/src/diff.rs#L59

Therefore, even if the actual structure has not changed, but only the order has been switched, it will be displayed as a difference.

A.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-controller
  template:
    metadata:
      labels:
        app: some-controller
    spec:
      containers:
        - name: name
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: production
            - name: VERSION
              value: v1.0.0
```

B.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-controller
  template:
    metadata:
      labels:
        app: some-controller
    spec:
      containers:
        - name: name
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: v1.0.0
            - name: ENV
              value: production
```

Run `git diff --no-index A.yaml B.yaml`.
```diff
git diff --no-index A.yaml B.yaml                                                                                                                                                                                                                         [~]
diff --git a/A.yaml b/B.yaml
index bd7aa5e..16a49ab 100644
--- a/A.yaml
+++ b/B.yaml
@@ -24,7 +24,7 @@ spec:
           ports:
             - containerPort: 8080
           env:
-            - name: ENV
-              value: production
             - name: VERSION
               value: v1.0.0
+            - name: ENV
+              value: production
```

Although they are different, they do not actually change the resources on Kubernetes, since the order of the arrays is only swapped.

## Proposal
[homeport/dyff](https://github.com/homeport/dyff) is diff tool for YAML that can be generate the structed diff. Such a tool will ignore cases where the order of the listings has simply changed.

normal diff
```console
$ dyff between -o github A.yaml B.yaml                                                                                                                                                                                                                     

@@ spec.template.spec.containers.name.env @@
! ⇆ order changed
- ENV, VERSION
+ VERSION, ENV
```

structed diff (need `--ignore-order-changes`)
```console
$ dyff between --ignore-order-changes -o github A.yaml B.yaml                                                                                                                                                                                               
```

Of course, there are times when you want to check it as a difference, so it would be nice if it were offered as an option.
