### ISSUE TITLE
[Feature Request] Add lever to hydrate ApplicationSet-managed Applications with `argocd appset generate`

### ISSUE THREAD

**Issue by seanturner026** [dag-andersen/argocd-diff-preview#73]
ArgoCD recently added a really handy cli upgrade in the form of `argocd appset generate $appset_name.yaml -o yaml`. 

https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_appset_generate/

This takes one's `ApplicationSet` and hydrates or renders all of the `Application` manifests that would be created if the `ApplicationSet` were to be deployed. This command greatly improves the `ApplicationSet` development feedback loop in two ways:

1. One can run the CLI command and see what manifests are going to be changed if they're just making yaml templating changes
2. Alternatively one can also confirm that an `Application` is being generated properly e.g. I'm using a `git generator` and I add a new directory that's globbed by the wild card.

Currently the `ArgoCD Diff Preview` renders new `Applications` when they're added in a PR. I propose that the `ArgoCD Diff Preview` by default render the `Applications` that are created by an `ApplicationSet` via the CLI.

I think it could also be helpful to have the option of disable this behavior (e.g. `argocd appset generate -o yaml` functionality) with an environment variable.

Consider your example from: https://github.com/dag-andersen/argocd-diff-preview/blob/ded37e62b69aa26289d3aae3e8a9d82b34fcba14/examples/helm/applications/my-app-set.yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: dev
      - name: prod
      - name: staging
  template:
    metadata:
      name: 'my-app-set-{{.name}}'
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: default
      sources:
        - repoURL: https://github.com/dag-andersen/argocd-diff-preview
          ref: local-files
        - path: examples/helm/charts/myApp
          repoURL: https://github.com/dag-andersen/argocd-diff-preview
          helm:
            valueFiles:
              - $local-files/examples/helm/values/my-app-set.yaml
```

If I were to open a PR adding a new enviornment...

```diff
      - name: dev
      - name: prod
      - name: staging
+     - name: uat
```

I would expect the `ArgoCD Diff Generator` to render an `Application` for UAT.
