### ISSUE TITLE
thread 'main' panicked at src/argo_resource.rs:26:59:

### ISSUE THREAD

**Issue by ImIOImI** [dag-andersen/argocd-diff-preview#83]
When running the github action with the following configuration:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: pull-request

      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Prepare secrets
        run: |
          mkdir secrets
          cat > secrets/secret.yaml << "EOF"
          apiVersion: v1
          kind: Secret
          metadata:
            name: private-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            url: https://github.com/${{ github.repository }}
            password: ${{ secrets.GITHUB_TOKEN }}
            username: not-used
          EOF          

      - name: Generate Diff
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -v $(pwd)/secrets:/secrets \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:v0.0.27

      - name: Post diff as comment
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'm getting the following logs:
```bash
Status: Downloaded newer image for dagandersen/argocd-diff-preview:v0.0.27
✨ Running with:
✨ - local-cluster-tool: Kind
✨ - cluster-name: argocd-diff-preview
✨ - base-branch: main
✨ - target-branch: 
✨ - secrets-folder: ./secrets
✨ - output-folder: ./output
✨ - argocd-namespace: argocd
✨ - repo: SumerSports/infra
✨ - timeout: 180 seconds
🤖 Fetching all files in dir: base-branch
🤖 Found 82 applications
🤖 Patching applications for branch: main
🤖 Patching 82 Argo CD Application[Sets] for branch: main
🤖 Fetching all files in dir: target-branch
🤖 Found 82 applications
🤖 Patching applications for branch: 
🤖 Patching 82 Argo CD Application[Sets] for branch: 
💾 Writing applications from 'main' to ./apps_base_branch.yaml
thread 'main' panicked at src/argo_resource.rs:26:[59](https://github.com/SumerSports/infra/actions/runs/12562419676/job/35022820241#step:5:60):
called `Result::unwrap()` on an `Err` value: Error { kind: EMITTER, problem: "expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 101.
```

Is there anything I'm doing wrong, here?

**Comment by dag-andersen** [comment]
Hi @ImIOImI,
Thank you for reporting this! I haven’t seen this issue before.

It seems like it’s having trouble reading one of your files as valid YAML.
Are you using aliases in your YAML files? 🤔 
The serde YAML library might not support them.

**Comment by dag-andersen** [comment]
Try using `v0.0.28` (released half an hour ago), as it _should_ print which Application the tool fails to convert to a string 🚀

**Comment by ImIOImI** [comment]
Ok, that helps... I got this:
```shell
❌ Failed to convert application 'gh-notifications-{{.Values.global.clusterName}}' (path: charts/aws-system/templates/argo-rollouts.yaml) to valid YAML: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS
```

What I _believe_ is happening is that I have a hub and spoke architecture and each cluster's bootstrap config is defined in terraform and not in the repo that holds all my argo config. 

I might have to figure out how to mock that config.

**Comment by dag-andersen** [comment]
@ImIOImI 
Would you mind posting the `charts/aws-system/templates/argo-rollouts.yaml` file here? :) I’d like to understand what’s going wrong and possibly come up with a general solution to the problem

**Comment by ImIOImI** [comment]
We have an aws-system helm chart and this is the `charts/aws-system/templates/argo-rollouts.yaml` template:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: argo-rollouts-{{.Values.global.clusterName}}
spec:
  destination:
    namespace: argo-rollouts
    server: {{ .Values.global.destination.server }}
  project: system
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.37.3
    helm:
      values: |
        notifications:
          configmap:
            create: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: gh-notifications-{{.Values.global.clusterName}}
spec:
  destination:
    namespace: argo-rollouts
    server: {{ .Values.global.destination.server }}
  project: system
  source:
    repoURL: https://github.com/SumerSports/infra
    targetRevision: github-rollouts-notifications-0.2.4
    path: "charts/github-rollouts-notifications"
    helm:
      parameters:
        - name: environment
          value: {{ .Values.global.environment }}
        - name: argocdUrl
          value: {{ .Values.global.hubURL }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
```

The relevant part of the values file looks like this:
```yaml
global:
  environment: "development"
  hubURL: "<redacted>"
  valuesScope: "aws"
  region: "us-east-1"
  clusterName: eks-cluster-name
  destination:
    server: https://kubernetes.default.svc
```
