### ISSUE TITLE
Support for updating revision in ApplicationSet git generators as well to the sources section

### ISSUE THREAD

**Issue by dedri-github** [dag-andersen/argocd-diff-preview#92]
Hi,
When working with ApplicationSets, we are using git generators to retrieve some attributes which are used on the Application template for that ApplicationSet. In order to have the full diff presented to us, when the tool patches the ApplicationSet to update the git revision, it does so in the Application template, but doesn't do it on the git generators section of the ApplicationSet.
Please note that we used nested generators (matrix within matrix with a git generator inside).

This is an example ApplicationSet we use:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - matrix:
              generators:
                - git:
                    repoURL: 'ssh://git@github.com/comp-something/something-{{.metadata.annotations.repo}}-cluster-overrides.git'
                    revision: HEAD
                    files:
                      - path: "customers/infra/{{.name}}/cluster-config.yaml"
                - git:
                    repoURL: 'ssh://git@github.com/comp-something/something-{{.metadata.annotations.repo}}-cluster-overrides.git'
                    revision: HEAD
                    files:
                      - path: "customers/*/{{.name}}/cluster-overrides/myapp.yaml"
                    pathParamPrefix: target
      selector:
        matchExpressions:
          - {key: 'apps.myapp', operator: Exists}
  template:
    metadata:
      name: "{{.name}}-myapp-app"
    spec:
      project: "default"
      sources:
        - repoURL: somethinghelmregistry.azurecr.io/helm
          chart: 'myapp'
          targetRevision: '{{.apps.myapp}}'
          helm:
            releaseName: 'myapp'
            valueFiles:
              - $values/global.yaml
              - $values/environment/{{.environment}}/infra/myapp.yaml
              - $values/customers/{{index .target.path.segments 1}}/{{.name}}/cluster-overrides/myapp.yaml
        - repoURL: "git@github.com:comp-something/something-{{.metadata.annotations.repo}}-cluster-overrides.git"
          targetRevision: '{{ .gitTag }}'
          ref: values
      destination:
        server: '{{.server}}'
        namespace: 'storage'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

It could be seen in the example above that we use the same repository specification (`comp-something/something-{{.metadata.annotations.repo}}-cluster-overrides.git`) on both the `sources` section of the template, and in the `generators` section.
We'd need the git generator's `ref` field to be updated with the base branch and target branch for the relevant repository which is provided with `--repo`, in addition to the `sources` section.
