### ISSUE TITLE
Can this be used for other Git providers or is only github supported?

### ISSUE THREAD

**Issue by jjlauterbach** [dag-andersen/argocd-diff-preview#94]
I'm looking to adopt this tool but am unsure how to use it outside of Github.  The `--repo` argument seems to be very specific to github's owner/repository format.  Can I specify a git url to a bitbucket repo?

**Comment by dag-andersen** [comment]
Hi, @jjlauterbach !

I have never used BitBucket, so i have not verified if it works or not.

Google tells me that the repo URLs look like this: `https://<your_username>@bitbucket.org/<workspace_ID>/<repo_name>.git`.
Is that right?

**Comment by jjlauterbach** [comment]
In our case we are running bitbucket data center so its a company base url but yes the path portion is something like `workspace/repo.git`

**Comment by dag-andersen** [comment]
Hi @jjlauterbach 
The `--repo` argument is used to find the `repoURL` in the Application manifests - So in the case of Bitbucket, you can still write `--repo=workspace/repo` and it should work 🚀 

In the case of GitHub, `${{ github.repository }}` is just a variable that prints `owner/repo`.

`argocd-diff-preview` is not GitHub specific.
I hope that helps.

Example: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  sources:
    - path: examples/helm/charts/myApp
      repoURL: https://github.com/dag-andersen/argocd-diff-preview ⬅️⬅️⬅️ # --repo=dag-andersen/argocd-diff-preview
    # OR in the case of Bitbucket: 
    # repoURL: https://<your_username>@bitbucket.org/<workspace_ID>/<repo_name> ⬅️⬅️⬅️ # --repo=<workspace_ID>/<repo_name>
      helm:
        valueFiles:
          - ...
```
